const cfg=window.KEEPS_CONFIG||{};let booked=new Set(cfg.DEMO_BOOKED_DATES||[]),selected=null,view=new Date(2026,11,1);const launch=new Date((cfg.LAUNCH_DATE||'2026-12-04')+'T00:00:00');
const pad=n=>String(n).padStart(2,'0');const key=d=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;
async function loadAvailability(){if(!cfg.API_URL)return;try{const r=await fetch(`${cfg.API_URL}?action=availability&t=${Date.now()}`);const j=await r.json();if(j.ok&&Array.isArray(j.confirmedDates))booked=new Set(j.confirmedDates);render();}catch(e){console.warn('Availability service unavailable; showing demo dates.',e)}}
function render(){const y=view.getFullYear(),m=view.getMonth(),label=document.getElementById('monthLabel'),cal=document.getElementById('calendar');label.textContent=view.toLocaleString('en-IN',{month:'long',year:'numeric'});cal.innerHTML='';for(let i=0;i<new Date(y,m,1).getDay();i++){let x=document.createElement('button');x.className='day blank';x.disabled=true;cal.appendChild(x)}const days=new Date(y,m+1,0).getDate();for(let n=1;n<=days;n++){let d=new Date(y,m,n),k=key(d),b=document.createElement('button');b.className='day';b.textContent=n;if(d<launch){b.disabled=true;b.classList.add('unavailable');b.title='Bookings open 4 December 2026'}else if(booked.has(k)){b.disabled=true;b.classList.add('booked');b.title='Booked'}else{b.onclick=()=>selectDate(k);if(selected===k)b.classList.add('selected')}cal.appendChild(b)}}
function selectDate(k){selected=k;document.getElementById('eventDate').value=k;document.getElementById('continueBtn').textContent=`Continue with ${new Date(k+'T00:00:00').toLocaleDateString('en-IN',{day:'numeric',month:'short',year:'numeric'})} →`;document.getElementById('continueBtn').classList.remove('disabled');document.getElementById('continueBtn').setAttribute('aria-disabled','false');render()}
document.getElementById('prevMonth').onclick=()=>{view=new Date(view.getFullYear(),view.getMonth()-1,1);if(view<new Date(2026,11,1))view=new Date(2026,11,1);render()};document.getElementById('nextMonth').onclick=()=>{view=new Date(view.getFullYear(),view.getMonth()+1,1);render()};
document.getElementById('eventDate').addEventListener('change',e=>{if(booked.has(e.target.value)){alert('That date has already been confirmed as booked. Please choose another date.');e.target.value='';selected=null;return}selected=e.target.value||null;render()});
document.querySelector('.menu').onclick=e=>{const nav=document.querySelector('nav');nav.classList.toggle('open');e.currentTarget.setAttribute('aria-expanded',nav.classList.contains('open'))};
document.getElementById('bookingForm').addEventListener('submit',async e=>{e.preventDefault();const status=document.getElementById('formStatus'),fd=new FormData(e.currentTarget),data=Object.fromEntries(fd.entries());if(booked.has(data.eventDate)){status.className='form-status full error';status.textContent='That date has just been booked. Please choose another date.';return}if(!cfg.API_URL){status.className='form-status full error';status.textContent='Demo mode: connect your Google Apps Script URL in config.js before accepting live inquiries.';return}status.className='form-status full';status.textContent='Sending your inquiry…';try{const r=await fetch(cfg.API_URL,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action:'submitInquiry',...data})});const j=await r.json();if(!j.ok)throw new Error(j.message||'Could not submit');status.className='form-status full success';status.textContent='We got your request ♡ Your date isn’t reserved just yet. A KEEPS team member will contact you on WhatsApp to confirm availability and finalize your booking.';e.currentTarget.reset();selected=null;render();await loadAvailability()}catch(err){status.className='form-status full error';status.textContent=err.message||'Something went wrong. Please try again.'}});
render();loadAvailability();
